theme: jekyll-theme-slate
title: CI/CD Full Pipeline Project
description: "TTS DevOps Cohort 2018 project using Jenkins, Artifactory, and Heroku to automagically deploy and manage a full-stack MEAN application"
show_downloads: false